### PR TITLE
removed redundant SPARK_WORKER_CORES env setting

### PR DESCRIPTION
**Pull request by inthecloud247**

### CODE REVIEW

**Comment by AndreSchumacher** [comment]
Hi,
Thanks for the input but are you sure that is actually redundant? Is there anything else that sets the number of cores to 1 per worker? (note: we do not want to use all cores for each worker, which AFAIK is the default) As of now it's still a valid environment variable, see:

 http://spark.incubator.apache.org/docs/latest/spark-standalone.html

**Comment by inthecloud247** [comment]
There are actually 2 entries in that same file...

**Comment by AndreSchumacher** [comment]
Uhh.. sorry, OK, merged it. Thanks.

**Comment by inthecloud247** [comment]
cool!

**Pull request merged**
